import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css"
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Icons } from "react-toastify";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LDU Downloader",
  description: "Generated by create next app",
  icons:{
    icon : "/Logo.png"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
   <head>
        {/* ✅ Explicitly add favicon */}
        <link rel="icon" href="/lo-1.svg" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
   style={{
        // backgroundImage: "url('/bg-main.jpg')",
        // backgroundSize: "cover",
        // backgroundPosition: "center",
        // height: "500px",
        // color: "white",
      }}      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
